version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.8.2

executors:
  default:
    docker:
      - image: circleci/python:3.8

workflows:
  unit-test:
    jobs:
      - unit-test
  build-and-push-image:
    jobs:
      - aws-ecr/build-and-push-image:
          repo: "${ECR_REPOSITORY}"
          tag: "${CIRCLE_SHA1}"
          filters:
            branches:
              only:
                - dev
                - stg
                - production

jobs:
  unit-test:
    executor:
        name: default
    steps:
      - checkout
      - run:
          name: Custom Settings
          command: |
            # ========== Custom Settings ==========
            # Please install the libraries if necessary.
            # For example: "sudo apt-get update && sudo apt-get install -y curl"
            #
            # ========== END ==========
      - restore_cache:
          key: podder-task-base-dependency-cache-{{ checksum "pyproject.toml" }}
      - run:
          name: Install requirements
          command: |
            pip install -U pip poetry setuptools
            poetry install
      - save_cache:
          key: v1-dependency-cache-{{ checksum "pyproject.toml" }}
          paths:
            - /home/circleci/.cache/pypoetry/virtualenvs
      - run:
          name: Run pytest
          command: |
            poetry run pytest tests/
